### ISSUE TITLE
Controller funktionstüchtig machen

### ISSUE THREAD

**Issue by StereoXDHBWFN** [StereoXDHBWFN/HTC-Vive#4]
Momentan werden die Controller in der Testszene nicht erkannt. Diese müssen allerdings erkannt und auch verwendet werden können, um die Anforderungen an das Projekt umsetzen zu können

**Comment by Inso666** [comment]
Nur mit Status schließen

**Comment by me-el-nino** [comment]
Laden des Skripts "Steam VR_UpdatePoses" in "Camera (Eye)" zeigt Kontroller.
