### ISSUE TITLE
Interaktion von Controller mit virtuellen Objekten

### ISSUE THREAD

**Issue by StereoXDHBWFN** [StereoXDHBWFN/HTC-Vive#5]
Die Controller müssen mit den Objekten im virtuellen Raum interagieren können (Aufnehmen, drehen etc.)

**Comment by StereoXDHBWFN** [comment]
Durch Bewegungen der Controller soll das Objekt auch vergrößert bzw. verkleinert werden können

**Comment by me-el-nino** [comment]
Das Aufnehmen, Bewegen und Drehen von Objekten funktioniert durch die ViveGrip Library. Zweihändige Interaktionen wie Vergrößern und Verkleinern noch nicht.

**Comment by me-el-nino** [comment]
Bewegen, Drehen und Größe ändern funktioniert jetzt.
