### ISSUE TITLE
Kollisionsabfrage von Objekten

### ISSUE THREAD

**Issue by StereoXDHBWFN** [StereoXDHBWFN/HTC-Vive#6]
Virtuelle Objekte dürfen nicht durch den Boden hindurch bewegt werden

**Comment by Inso666** [comment]
Auch hier nur mit Status schließen

**Comment by me-el-nino** [comment]
Funktioniert. Nicht sicher, ob native durch Unity oder durch SteamVR oder durch ViveGrip.
