### ISSUE TITLE
Kamera der Brille aktivieren und verwenden

### ISSUE THREAD

**Issue by StereoXDHBWFN** [StereoXDHBWFN/HTC-Vive#7]
Die in der Brille eingebaute Kamera kann verwendet werden, um sich besser im Raum orientieren zu können. Dies soll auch im Projekt verwendet werden

**Comment by Inso666** [comment]
läuft, läuft nicht? bitte nur mit Status schließen

**Comment by me-el-nino** [comment]
Funktioniert mit Doppelklick auf Menü. Wenn aktiviert, werden Objekte aus der Szene noch dargestellt aber man kann nicht mehr mit diesen interagieren.
