### ISSUE TITLE
Umwandlung von STL Datei in ein von Unity lesbares Format

### ISSUE THREAD

**Issue by Inso666** [StereoXDHBWFN/HTC-Vive#8]
Nach Recherche ist STL wohl das zu empfehlende Format für den Export aus einer CAD Software (Catia). Da dies jedoch nicht in Unity geladen werden kann, muss vorher das Format konvertiert werden. Am besten in .obj.
Die kann mithilfe von Blender realisiert werden. 
Blender kann ebenfalls durch python gesteuert werden (Python)

**Comment by Inso666** [comment]
Skript ist mit Testdatei hochgeladen. Funktioniert, wenn es aus dem Blender ordner aufgerufen wird. Alternativ blender zum PATH hinzufügen

**Comment by StereoXDHBWFN** [comment]
Import funktioniert

- VRTK_Interactable Object
- VRTK_Fixed Joint Grab Attach
- VRTK_Axis Scale Grab Action

müssen hinzugefügt werden

Desweiteren müssen für die einzelnen Meshes im Mesh Collider Script Convex angewählt werden
